create or replace semantic view REPORT_TABLE_SV
	tables (
		<database>.<schema>.REPORT_TABLE
	)
	facts (
		REPORT_TABLE.COST as COST comment='The cost or expense amount in dollars associated with the record.',
		REPORT_TABLE.DISCOUNT_PERCENT as DISCOUNT_PERCENT comment='The discount percentage applied to the record, as a decimal (e.g. 0.15 = 15%).',
		REPORT_TABLE.REVENUE as REVENUE comment='The revenue or income amount in dollars generated by the record.',
		REPORT_TABLE.TAX_RATE as TAX_RATE comment='The tax rate applied to the record, as a decimal (e.g. 0.08 = 8%).',
		REPORT_TABLE.TOTAL_AMOUNT as TOTAL_AMOUNT comment='The total dollar amount for the record after all adjustments.',
		REPORT_TABLE.UNIT_PRICE as UNIT_PRICE comment='The price per unit in dollars.',
		REPORT_TABLE.WEIGHT_KG as WEIGHT_KG comment='The weight of the item in kilograms.'
	)
	dimensions (
		REPORT_TABLE.ASSIGNED_TO as ASSIGNED_TO comment='The person or team member assigned to the report record.',
		REPORT_TABLE.CATEGORY as CATEGORY comment='The functional category of the record such as Marketing, Engineering, HR, Sales, etc.',
		REPORT_TABLE.COUNTRY_CODE as COUNTRY_CODE comment='Three-letter ISO country code indicating the country of origin for the record.',
		REPORT_TABLE.CUSTOMER_EMAIL as CUSTOMER_EMAIL comment='The email address of the customer associated with the record.',
		REPORT_TABLE.DEPARTMENT as DEPARTMENT comment='The department responsible for the record, such as Business Development, Customer Success, Research, etc.',
		REPORT_TABLE.DESCRIPTION as DESCRIPTION comment='Free-text description of the report record.',
		REPORT_TABLE.IS_ACTIVE as IS_ACTIVE comment='Whether the record is currently active (true) or inactive/archived (false).',
		REPORT_TABLE.NOTES as NOTES comment='Additional notes or comments associated with the record.',
		REPORT_TABLE.PRIORITY as PRIORITY comment='Priority level of the record, where lower numbers indicate higher priority.',
		REPORT_TABLE.QUANTITY as QUANTITY comment='The quantity or count of items associated with the record.',
		REPORT_TABLE.RATING as RATING comment='A numeric rating or score assigned to the record.',
		REPORT_TABLE.REGION as REGION comment='The geographic region for the record: NA (North America), EMEA (Europe/Middle East/Africa), APAC (Asia-Pacific), LATAM (Latin America), ANZ (Australia/New Zealand), MEA (Middle East/Africa).',
		REPORT_TABLE.REPORT_ID as REPORT_ID comment='Unique numeric identifier for each report record.',
		REPORT_TABLE.REPORT_NAME as REPORT_NAME comment='The name or title of the report record.',
		REPORT_TABLE.STATUS as STATUS comment='The current status of the record: Open, Pending, or Closed.',
		REPORT_TABLE.CREATED_DATE as CREATED_DATE comment='The date when the record was originally created.',
		REPORT_TABLE.START_TIME as START_TIME comment='The time of day when the record activity started.',
		REPORT_TABLE.SUBMITTED_AT as SUBMITTED_AT comment='The timestamp when the record was submitted for review or processing.',
		REPORT_TABLE.UPDATED_TIMESTAMP as UPDATED_TIMESTAMP comment='The timestamp of the most recent update to the record.'
	)
	comment='A demo report table for semantic view demonstration, containing report tracking data with financial metrics, categorical dimensions, and temporal attributes.'
	ai_verified_queries (
		TOTAL_REVENUE_BY_REGION AS (
			QUESTION 'What is the total revenue by region?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION true
			SQL 'SELECT REGION, SUM(REVENUE) AS TOTAL_REVENUE FROM <database>.<schema>.REPORT_TABLE WHERE REVENUE IS NOT NULL GROUP BY 1 ORDER BY 2 DESC'),
		TOTAL_REVENUE_BY_DEPARTMENT AS (
			QUESTION 'What is the total revenue by department?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION true
			SQL 'SELECT DEPARTMENT, SUM(REVENUE) AS TOTAL_REVENUE FROM <database>.<schema>.REPORT_TABLE WHERE REVENUE IS NOT NULL GROUP BY 1 ORDER BY 2 DESC'),
		MONTHLY_REVENUE_TREND AS (
			QUESTION 'How does revenue trend over time by month?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION true
			SQL 'SELECT DATE_TRUNC(''MONTH'', CREATED_DATE) AS MONTH, SUM(REVENUE) AS TOTAL_REVENUE FROM <database>.<schema>.REPORT_TABLE WHERE CREATED_DATE IS NOT NULL AND REVENUE IS NOT NULL GROUP BY 1 ORDER BY 1'),
		MONTHLY_COST_TREND AS (
			QUESTION 'How does cost trend over time by month?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT DATE_TRUNC(''MONTH'', CREATED_DATE) AS MONTH, SUM(COST) AS TOTAL_COST FROM <database>.<schema>.REPORT_TABLE WHERE CREATED_DATE IS NOT NULL AND COST IS NOT NULL GROUP BY 1 ORDER BY 1'),
		TOP_10_REGIONS_BY_REVENUE AS (
			QUESTION 'What are the top 10 regions by revenue?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION true
			SQL 'SELECT REGION, SUM(REVENUE) AS TOTAL_REVENUE FROM <database>.<schema>.REPORT_TABLE WHERE REVENUE IS NOT NULL GROUP BY 1 ORDER BY 2 DESC LIMIT 10'),
		AVERAGE_COST_BY_DEPARTMENT AS (
			QUESTION 'What is the average cost by department?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT DEPARTMENT, AVG(COST) AS AVG_COST FROM <database>.<schema>.REPORT_TABLE WHERE COST IS NOT NULL GROUP BY 1 ORDER BY 2 DESC'),
		TOTAL_AMOUNT_BY_CATEGORY AS (
			QUESTION 'What is the total amount by category?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT CATEGORY, SUM(TOTAL_AMOUNT) AS TOTAL_AMOUNT FROM <database>.<schema>.REPORT_TABLE WHERE TOTAL_AMOUNT IS NOT NULL GROUP BY 1 ORDER BY 2 DESC'),
		REVENUE_BY_STATUS AS (
			QUESTION 'What is the revenue breakdown by status?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT STATUS, SUM(REVENUE) AS TOTAL_REVENUE FROM <database>.<schema>.REPORT_TABLE WHERE REVENUE IS NOT NULL GROUP BY 1 ORDER BY 2 DESC'),
		MONTHLY_REVENUE_BY_REGION AS (
			QUESTION 'What is the monthly revenue by region?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT DATE_TRUNC(''MONTH'', CREATED_DATE) AS MONTH, REGION, SUM(REVENUE) AS TOTAL_REVENUE FROM <database>.<schema>.REPORT_TABLE WHERE CREATED_DATE IS NOT NULL AND REVENUE IS NOT NULL GROUP BY 1, 2 ORDER BY 1, 2'),
		RECORD_COUNT_BY_DEPARTMENT AS (
			QUESTION 'How many records are there by department?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT DEPARTMENT, COUNT(*) AS RECORD_COUNT FROM <database>.<schema>.REPORT_TABLE GROUP BY 1 ORDER BY 2 DESC'),
		AVERAGE_RATING_BY_CATEGORY AS (
			QUESTION 'What is the average rating by category?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT CATEGORY, AVG(RATING) AS AVG_RATING FROM <database>.<schema>.REPORT_TABLE WHERE RATING IS NOT NULL GROUP BY 1 ORDER BY 2 DESC'),
		REVENUE_VS_COST_BY_DEPARTMENT AS (
			QUESTION 'How does revenue compare to cost by department?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION true
			SQL 'SELECT DEPARTMENT, SUM(REVENUE) AS TOTAL_REVENUE, SUM(COST) AS TOTAL_COST, SUM(REVENUE) - SUM(COST) AS PROFIT FROM <database>.<schema>.REPORT_TABLE WHERE REVENUE IS NOT NULL AND COST IS NOT NULL GROUP BY 1 ORDER BY 4 DESC'),
		WEEKLY_TOTAL_AMOUNT_TREND AS (
			QUESTION 'What is the weekly total amount trend?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT DATE_TRUNC(''WEEK'', CREATED_DATE) AS WEEK, SUM(TOTAL_AMOUNT) AS TOTAL_AMOUNT FROM <database>.<schema>.REPORT_TABLE WHERE CREATED_DATE IS NOT NULL AND TOTAL_AMOUNT IS NOT NULL GROUP BY 1 ORDER BY 1'),
		TOP_5_DEPARTMENTS_BY_COST AS (
			QUESTION 'What are the top 5 departments by cost?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT DEPARTMENT, SUM(COST) AS TOTAL_COST FROM <database>.<schema>.REPORT_TABLE WHERE COST IS NOT NULL GROUP BY 1 ORDER BY 2 DESC LIMIT 5'),
		QUANTITY_BY_REGION AS (
			QUESTION 'What is the total quantity by region?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT REGION, SUM(QUANTITY) AS TOTAL_QUANTITY FROM <database>.<schema>.REPORT_TABLE WHERE QUANTITY IS NOT NULL GROUP BY 1 ORDER BY 2 DESC'),
		REVENUE_BY_COUNTRY AS (
			QUESTION 'What is the total revenue by country?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT COUNTRY_CODE, SUM(REVENUE) AS TOTAL_REVENUE FROM <database>.<schema>.REPORT_TABLE WHERE REVENUE IS NOT NULL GROUP BY 1 ORDER BY 2 DESC'),
		ACTIVE_VS_INACTIVE_REVENUE AS (
			QUESTION 'How does revenue differ between active and inactive records?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT IS_ACTIVE, SUM(REVENUE) AS TOTAL_REVENUE, COUNT(*) AS RECORD_COUNT FROM <database>.<schema>.REPORT_TABLE WHERE REVENUE IS NOT NULL GROUP BY 1 ORDER BY 2 DESC'),
		AVG_UNIT_PRICE_BY_CATEGORY AS (
			QUESTION 'What is the average unit price by category?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT CATEGORY, AVG(UNIT_PRICE) AS AVG_UNIT_PRICE FROM <database>.<schema>.REPORT_TABLE WHERE UNIT_PRICE IS NOT NULL GROUP BY 1 ORDER BY 2 DESC'),
		TOTAL_COST_BY_REGION_AND_DEPARTMENT AS (
			QUESTION 'What is the total cost by region and department?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT REGION, DEPARTMENT, SUM(COST) AS TOTAL_COST FROM <database>.<schema>.REPORT_TABLE WHERE COST IS NOT NULL GROUP BY 1, 2 ORDER BY 3 DESC'),
		OPEN_RECORDS_BY_REGION AS (
			QUESTION 'How many open records are there by region?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT REGION, COUNT(*) AS OPEN_COUNT FROM <database>.<schema>.REPORT_TABLE WHERE STATUS = ''Open'' GROUP BY 1 ORDER BY 2 DESC'),
		AVG_DISCOUNT_BY_DEPARTMENT AS (
			QUESTION 'What is the average discount percentage by department?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT DEPARTMENT, AVG(DISCOUNT_PERCENT) AS AVG_DISCOUNT FROM <database>.<schema>.REPORT_TABLE WHERE DISCOUNT_PERCENT IS NOT NULL GROUP BY 1 ORDER BY 2 DESC'),
		HIGH_PRIORITY_RECORDS_BY_STATUS AS (
			QUESTION 'How many high priority records are there by status?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT STATUS, COUNT(*) AS RECORD_COUNT FROM <database>.<schema>.REPORT_TABLE WHERE PRIORITY <= 3 GROUP BY 1 ORDER BY 2 DESC'),
		MONTHLY_RECORD_VOLUME AS (
			QUESTION 'How many records are created each month?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT DATE_TRUNC(''MONTH'', CREATED_DATE) AS MONTH, COUNT(*) AS RECORD_COUNT FROM <database>.<schema>.REPORT_TABLE WHERE CREATED_DATE IS NOT NULL GROUP BY 1 ORDER BY 1'),
		REVENUE_BY_CATEGORY_AND_STATUS AS (
			QUESTION 'What is the revenue by category and status?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT CATEGORY, STATUS, SUM(REVENUE) AS TOTAL_REVENUE FROM <database>.<schema>.REPORT_TABLE WHERE REVENUE IS NOT NULL GROUP BY 1, 2 ORDER BY 3 DESC'),
		TOTAL_WEIGHT_BY_REGION AS (
			QUESTION 'What is the total weight shipped by region?'
			VERIFIED_AT 1713200000
			VERIFIED_BY '<user>'
			ONBOARDING_QUESTION false
			SQL 'SELECT REGION, SUM(WEIGHT_KG) AS TOTAL_WEIGHT_KG FROM <database>.<schema>.REPORT_TABLE WHERE WEIGHT_KG IS NOT NULL GROUP BY 1 ORDER BY 2 DESC')
	);
